import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { api } from "../../api/client";
import { Device } from "../../types";

type DeviceFormValues = { name: string; vendor: string; ipAddress?: string; port?: string; serialNumber?: string; deviceType: string; location?: string; username?: string; password?: string; apiKey?: string; apiSecret?: string; baseUrl?: string; siteCode?: string; isActive?: boolean; };
type Props = { open: boolean; onClose: () => void; initialData?: Device; onSuccess?: () => void; };
export default function DeviceModal({ open, onClose, initialData, onSuccess }: Props) {
  const { register, handleSubmit, reset, watch } = useForm<DeviceFormValues>(); const vendor = watch("vendor");
  useEffect(() => {
    if (!open) return;
    if (initialData) reset({ name: initialData.name, vendor: initialData.vendor, ipAddress: initialData.ipAddress || "", port: initialData.port ? String(initialData.port) : "", serialNumber: initialData.serialNumber || "", deviceType: initialData.deviceType, location: initialData.location || "", username: initialData.username || "", password: initialData.password || "", apiKey: initialData.apiKey || "", apiSecret: initialData.apiSecret || "", baseUrl: initialData.baseUrl || "", siteCode: initialData.siteCode || "", isActive: initialData.isActive });
    else reset({ name: "", vendor: "MOCK", ipAddress: "", port: "", serialNumber: "", deviceType: "Attendance Terminal", location: "", username: "", password: "", apiKey: "", apiSecret: "", baseUrl: "", siteCode: "", isActive: true });
  }, [open, initialData, reset]);
  const onSubmit = async (data: DeviceFormValues) => { if (initialData?.id) await api.put(`/devices/${initialData.id}`, data); else await api.post("/devices", data); onSuccess?.(); onClose(); };
  if (!open) return null;
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-3xl rounded-2xl bg-white shadow-xl"><div className="flex items-center justify-between border-b px-6 py-4"><h3 className="text-lg font-semibold">{initialData ? "Edit Device" : "Add Device"}</h3><button onClick={onClose} className="text-xl leading-none">×</button></div><form onSubmit={handleSubmit(onSubmit)} className="grid grid-cols-1 gap-4 p-6 md:grid-cols-2"><input className="rounded border p-3" placeholder="Device Name" {...register("name", { required: true })} /><select className="rounded border p-3" {...register("vendor", { required: true })}><option value="MOCK">Mock</option><option value="ZKTECO">ZKTeco</option><option value="HIKVISION">Hikvision</option><option value="ANVIZ">Anviz</option><option value="SUPREMA">Suprema</option></select><input className="rounded border p-3" placeholder="IP Address" {...register("ipAddress")} /><input className="rounded border p-3" placeholder="Port" {...register("port")} /><input className="rounded border p-3" placeholder="Serial Number" {...register("serialNumber")} /><input className="rounded border p-3" placeholder="Device Type" {...register("deviceType", { required: true })} /><input className="rounded border p-3" placeholder="Location" {...register("location")} /><input className="rounded border p-3" placeholder="Base URL" {...register("baseUrl")} />{(vendor === "HIKVISION" || vendor === "SUPREMA") && <><input className="rounded border p-3" placeholder="Username" {...register("username")} /><input className="rounded border p-3" type="password" placeholder="Password" {...register("password")} /></>}{(vendor === "ZKTECO" || vendor === "ANVIZ" || vendor === "SUPREMA") && <><input className="rounded border p-3" placeholder="API Key" {...register("apiKey")} /><input className="rounded border p-3" placeholder="API Secret" {...register("apiSecret")} /></>}<input className="rounded border p-3" placeholder="Site Code" {...register("siteCode")} /><label className="flex items-center gap-2 rounded border p-3"><input type="checkbox" {...register("isActive")} /> Active</label><div className="flex justify-end gap-3 pt-2 md:col-span-2"><button type="button" onClick={onClose} className="rounded border px-4 py-2">Cancel</button><button type="submit" className="rounded bg-blue-600 px-4 py-2 text-white">Save</button></div></form></div></div>;
}
