import { useQuery } from "@tanstack/react-query";
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, BarChart, Bar } from "recharts";
import { api } from "../api/client";
function Card({ title, value }: { title: string; value: string | number }) { return <div className="rounded-xl bg-white p-5 shadow"><div className="text-sm text-gray-500">{title}</div><div className="mt-2 text-2xl font-bold">{value}</div></div>; }
export default function DashboardPage() {
  const summaryQuery = useQuery({ queryKey: ["dashboard-summary"], queryFn: async () => (await api.get("/dashboard/summary")).data });
  const data = summaryQuery.data || { totalEmployees: 0, totalDevices: 0, todayLogs: 0, todayPresent: 0, chart: [] };
  return <div><h2 className="mb-4 text-2xl font-bold">Dashboard</h2><div className="mb-6 grid grid-cols-1 gap-4 md:grid-cols-4"><Card title="Total Employees" value={data.totalEmployees} /><Card title="Total Devices" value={data.totalDevices} /><Card title="Today Logs" value={data.todayLogs} /><Card title="Today Present" value={data.todayPresent} /></div><div className="mb-6 rounded-xl bg-white p-5 shadow"><h3 className="mb-4 text-lg font-semibold">Monthly Attendance Trend</h3><div className="h-80"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.chart}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="date" /><YAxis /><Tooltip /><Legend /><Line type="monotone" dataKey="present" stroke="#2563eb" /><Line type="monotone" dataKey="late" stroke="#f59e0b" /><Line type="monotone" dataKey="absent" stroke="#dc2626" /></LineChart></ResponsiveContainer></div></div><div className="rounded-xl bg-white p-5 shadow"><h3 className="mb-4 text-lg font-semibold">Monthly Attendance Bars</h3><div className="h-80"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.chart}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="date" /><YAxis /><Tooltip /><Legend /><Bar dataKey="present" fill="#2563eb" /><Bar dataKey="late" fill="#f59e0b" /><Bar dataKey="absent" fill="#dc2626" /></BarChart></ResponsiveContainer></div></div></div>;
}
